### ISSUE TITLE
[Suggestion] API - Set External HostURL

### ISSUE THREAD

**Issue by brettsaunders21** [LoneDev6/Issues-ItemsAdder#279]
**Is your feature request related to a problem? Please describe.**
When creating a plugin and using ItemsAdder as an API there is no way to easily add your custom textures and ItemPacks. Other than making the user manually do this which can create a barrier to the entry level required to use add-on.

**Describe the solution you'd like**
The most complete version would be either an API where you can pass your custom item packs and resources from the JAR to be copied.

OR a way to set the external hosting url through code, as it would be hard for a developer to edit the config without a concurrency exception.

**Additional Details**
Allow this is more complex if you were to implement a resource pack combiner, this would make this a lot easier.

**Comment by LoneDev6** [comment]
Interesting.
A good solution I have in mind would be this:
your custom plugin saves the needed data inside ItemsAdder data folder if not found when it loads and then triggers /iareload command.

This is the only way but I don't really like to automatize that because some admins would still need to do manual update the dropbox link in config.yml if they're using external-host instead of automatic self-host. This cannot be automated 100% for now. This automation could cause confusion I think

**Comment by LoneDev6** [comment]
Cancelled due to too complex and risky behaviour, it could lead to confusion to the average server admin
